version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./api:/app
      - ./data:/data
    ports:
     - "5001:500"
    depends_on:
      - redis
  worker:
    build:
      context: workers 
      dockerfile: Dockerfile
    volumes:
      - ./workers:/queue
    depends_on:
      - redis
  monitor:
    build:
      context: workers
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
    volumes: 
      - ./redis_data:/data
